import '../models/predio.dart';

final List<Predio> prediosIniciais = [
  Predio(
    id: 'escola',
    nome: 'Escola',
    categoria: 'Escola',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 30,
    y1: 200,
    x2: 130,
    y2: 300,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor:'#FFCC00',
  ),
  Predio(
    id: 'prefeitura',
    nome: 'Prefeitura',
    categoria: 'Prefeitura',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 300,
    y1: 160,
    x2: 400,
    y2: 260,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#00AAFF',
  ),
  Predio(
    id: 'hospital',
    nome: 'Hospital',
    categoria: 'Hospital',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 700,
    y1: 150,
    x2: 800,
    y2: 250,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#FF6666',
  ),
  Predio(
    id: 'financas',
    nome: 'Finanças',
    categoria: 'Finanças',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 250,
    y1: 600,
    x2: 350,
    y2: 700,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#00CC99',
  ),
  Predio(
    id: 'espiritual',
    nome: 'Espiritual',
    categoria: 'Espiritual',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 800,
    y1: 300,
    x2: 900,
    y2: 400,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#9966FF',
  ),
  Predio(
    id: 'lazer',
    nome: 'Lazer',
    categoria: 'Lazer',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 1000,
    y1: 250,
    x2: 1100,
    y2: 350,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#FF9900',
  ),
  Predio(
    id: 'familia_amigos',
    nome: 'Família e amigos',
    categoria: 'Família e amigos',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 1000,
    y1: 600,
    x2: 1100,
    y2: 700,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#FF66CC',
  ),
  Predio(
    id: 'moradia',
    nome: 'Moradia',
    categoria: 'Moradia',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 700,
    y1: 600,
    x2: 800,
    y2: 700,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '	#FF9966',
  ),
  Predio(
    id: 'horta',
    nome: 'Horta',
    categoria: 'Horta',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 20,
    y1: 500,
    x2: 120,
    y2: 600,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#66CC33',
  ),
  Predio(
    id: 'atelie',
    nome: 'Ateliê',
    categoria: 'Ateliê',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 50,
    y1: 300,
    x2: 150,
    y2: 400,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#FFCC99',
  ),
  Predio(
    id: 'cozinha',
    nome: 'Cozinha',
    categoria: 'Cozinha',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 300,
    y1: 360,
    x2: 400,
    y2: 460,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#FF6600',
  ),
  Predio(
    id: 'workshop',
    nome: 'Workshop',
    categoria: 'Workshop',
    nivel: 1,
    xpTotal: 0,
    xpDiario: 0,
    status: PredioStatus.ativo,
    x1: 550,
    y1: 400,
    x2: 650,
    y2: 500,
    imagens: [],
    habilidadesDesbloqueadas: [],
    orcamentoMensal: 0,
    orcamentoTotal: 0,
    cor: '#3399FF',
  ),
];